### ISSUE TITLE
Marginaler mellan botten sträck och text är för liten

### ISSUE THREAD

**Issue by NiklasPerssonMDU** [MDU-C2/LaTeX-Templates#2]
När en sida fylls med brödtext så är hamnar texten precis ovanför strecket, vilket får texten att se understrycken ut. Se nedan:

![image](https://github.com/MDU-C2/LaTeX-Templates/assets/100279902/1e03ba67-7f21-4414-8b3a-05370d0ea2de)

**Comment by Swepz** [comment]
Blir detta bra? 
![image](https://github.com/MDU-C2/LaTeX-Templates/assets/32343381/a259ab81-f525-4a6e-a4b5-d6f5dec4ec4a)

**Comment by NiklasPerssonMDU** [comment]
Om det är lika stort som whitespacet upptill mellan brödtext och linje så blir det super. Förstår att om det är figurer/tabeller emellan så kan de diffa lite, men ska inte vara någon stor skillnad mellan uppe och nere.

**Comment by Swepz** [comment]
Tror de är ungefär lika nu 
![image](https://github.com/MDU-C2/LaTeX-Templates/assets/32343381/f7d76a29-1e1c-487c-b6e5-b8e7848952ee)

**Comment by NiklasPerssonMDU** [comment]
Ser bra ut, tack!
