### ISSUE TITLE
Figurtext bör skiljas från brödtext

### ISSUE THREAD

**Issue by NiklasPerssonMDU** [MDU-C2/LaTeX-Templates#3]
I dagsläget har figurtexten samma font som brödtexten vilket kan förvirra. 

Mitt förslag är att man ändrar så att **Figure nr** skrivs ut i bold och _figurtexten_ är kursiv.

**Comment by Swepz** [comment]
Fungerar detta?

![image](https://github.com/MDU-C2/LaTeX-Templates/assets/32343381/2ec2e3a4-a2dd-46c9-81dc-f10f6ec20308)

**Comment by NiklasPerssonMDU** [comment]
Det blir bra! Tack
