### ISSUE TITLE
Ingen punkt i sections

### ISSUE THREAD

**Issue by NiklasPerssonMDU** [MDU-C2/LaTeX-Templates#4]
I dagsläget, när studenterna referear till en sektion, t.ex /ref{sec:intro} så kommer punkten också med vilket ser för tråkigt ut när man sedan har komma eller punkt efter:

![image](https://github.com/MDU-C2/LaTeX-Templates/assets/100279902/07551605-2a4c-474d-9b01-866a4e709170)

men också när man refererar till en sektion mitt i en mening så får man en punkt, fast utan att avsluta meningen:
![image](https://github.com/MDU-C2/LaTeX-Templates/assets/100279902/a64d18b0-3442-4083-a63a-df676547cafc)

Mitt förslag är att man tar punkten, så det blir: 
1 Introduction

istället för 
1. Introduction

**Comment by Swepz** [comment]
Blir detta bra? 
![image](https://github.com/MDU-C2/LaTeX-Templates/assets/32343381/7312ad3b-1924-4898-a77f-3bef57fecd9e)

**Comment by Swepz** [comment]
![image](https://github.com/MDU-C2/LaTeX-Templates/assets/32343381/0e41ef13-ae22-4a2d-bb9e-3d72abdaa65c)

**Comment by NiklasPerssonMDU** [comment]
Perfekt, tack!
